---
title: "FIGURE-CARING_FIESTA"
author: "CoraHoerstmann"
date: "2022-12-19"
output: html_document
---

```{r setup, include=FALSE}
require(dplyr)
require(tidyverse)
require(oce)
require(ocedata)
require(anytime) #date format is unambigious for base function
require(reshape2)

#for printing the oceanographic maps:
library("rnaturalearth")
library("rnaturalearthdata")
library("ggplot2")
library("sf")

#for 3D plots
library("plot3D") #IMPORTATNT: This needs XQUARTZ to run in the background
library(akima) #for the 3D extraploate representation
library(raster)
```


```{r physics, echo=FALSE, warning = FALSE, fig.width=7,fig.height=2.5, fig.show="hold", out.width="50%"}
 all_data <- read.csv("/Users/corahoerstmann/Documents/MIO_FIGURE/FIGURE_all_data.csv")
#CTD data and plot (to be adjusted)
source("/Users/corahoerstmann/Documents/MIO_FIGURE/oceanographic_data.R")

source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_CTD_log.R")


#note that this important subscripts are loaded:
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/oceanography_plots.R")
```
#import nutrients

```{r}
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_nutrients.R")
```

#import N2

```{r N2}
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_N2.R")
```


#import DNA data


```{r DNA}
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_DNA.R")
```


#Plots

```{r}
stationmap_CTD <- ggplot(data = world) +
  geom_sf() +
  
  geom_point(data = qPCR_UW, aes(x = Longitude, y = Latitude), size = 1, 
             shape = 23, fill = "orange") +
  geom_point(data = N2_UW, aes(x = Longitude, y = Latitude), size = 1, 
             shape = 23, fill = "gold1") +
  geom_point(data = CTD_N2, aes(x = Longitude, y = Latitude), size = 1.5, 
             shape = 23, fill = "darkgreen") +
  coord_sf(xlim = c(-85, -60), ylim = c(30, 45), expand = FALSE)

print(stationmap_CTD)


#NA_map <- ggplot(data = world) +
#  geom_sf() +
#coord_sf(xlim = c(-90, -50), ylim = c(25, 55), expand = FALSE)

#print(NA_map)


#calculate distance between points
#library("geosphere")
#my_points <- qPCR_UW[,c(28,29)]
#dist_mat <- distm(my_points, fun = distGeo)

```


```{r N2 plots, echo=FALSE}
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/N2_plots.R")
```

```{r qPCR plots, echo=FALSE}
#source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/")
```


## Sequence analysis

```{r}
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/data_transformation.R")
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_sequence_data.R")
source("/Users/corahoerstmann/Documents/MIO_FIGURE/scripts/import_16S.R")
```

CLR transformation
```{r}
nifH_ASV_CLR <- clr(nifH_ASV,1)
nifH_ait <- dczm(nifH_ASV,1)
nifH_taxonomy_CLR <- nifH_taxonomy_v2%>%filter(X %in% rownames(nifH_ASV_CLR))
```
multivariate analysis
```{r}

```

#eddys in the North Atlantic
```{r}
N2_structure_DB <- read.csv("/Users/corahoerstmann/Documents/MIO_FIGURE/N2_data/Satellite_N2_DB/N2_DB_compiled_Fine_scale_structures.csv")
N2_structure_DB$N2.Rate.nmol.L.1.d.1 <- as.numeric(N2_structure_DB$N2.Rate.nmol.L.1.d.1)

N2_structure_DB <- N2_structure_DB%>%filter(!Fine.scale.Structure..Open.Oean..coast.shelf == "unknown")

DB <- ggplot(data = N2_structure_DB, aes(x = Fine.scale.Structure..Open.Oean..coast.shelf, y = N2.Rate.nmol.L.1.d.1))+
  geom_violin(trim=FALSE)+
  ylim(0,100)+
  stat_summary(fun.y=median, geom="point", size=2, color="red")

print(DB)

```

